### ISSUE TITLE
AssertionError when reloading the page

### ISSUE THREAD

**Issue by falkoschindler** [justpy-org/justpy#469]
When running the following script

```python
#!/usr/bin/env python3
import justpy as jp

wp = jp.WebPage()
wp.add(jp.Div(text='Hello, world!'))

jp.justpy(lambda: wp)
```

and reloading the page *twice*, I get a 500 Server Error and the following traceback:

```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/homebrew/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/endpoints.py", line 42, in dispatch
    response = await handler(request)
  File "/Users/falko/Downloads/justpy/justpy/justpy.py", line 180, in get
    assert len(load_page) > 0 or load_page.html, '\u001b[47;1m\033[93mWeb page is empty, add components\033[0m'
AssertionError: Web page is empty, add components
```

Could it have something to do with https://github.com/justpy-org/justpy/pull/354?

Tested with Chrome or Firefox on https://github.com/justpy-org/justpy/commit/02e3d9fac264dd66424567552d315084a70e96d4

**Comment by WolfgangFahl** [comment]
I am in favor of making the old behavior optional which shouldn't be to much work.

**Comment by WolfgangFahl** [comment]
The question is also whether you expectation is correct - doesn the lambda create a new webpage and you are expecting that this is automatically magically exchanged with the existing one? Wouldn't you have to shut down and restart the whole server to do so?

**Comment by falkoschindler** [comment]
Apparently this behavior is not new. JustPy doesn't seem to like reusing `wp` objects.
