### ISSUE TITLE
aggrid grid_ready crashes when columnApi.getAllColumns() returns null

### ISSUE THREAD

**Issue by WolfgangFahl** [justpy-org/justpy#612]
```javascript
 function grid_ready(event) {
                if (auto_size) {
                    var allColumnIds = [];
                    grid_def.columnApi.getAllColumns().forEach(function (column) {
                        allColumnIds.push(column.colId);
                    });
                    grid_def.columnApi.autoSizeColumns(allColumnIds);
                }
            }
```

Happend as a followup error of
```python
LodGrid.load_lod() got an unexpected keyword argument 'columnDefs'
Traceback (most recent call last):
  File "/Users/wf/Documents/pyworkspace/pyCEURmake/ceurws/volumebrowser.py", line 497, in __init__
    self.agGrid.load_lod(lod)
  File "/Users/wf/Documents/pyworkspace/pyJustpyWidgets/jpwidgets/widgets.py", line 41, in load_lod
    self.load_pandas_frame(df)
  File "/Users/wf/Documents/pyworkspace/justpy/justpy/gridcomponents.py", line 138, in load_pandas_frame
    self.load_lod(lod=lod,columnDefs=columnDefs)
TypeError: LodGrid.load_lod() got an unexpected keyword argument 'columnDefs'
```

which might be just a configuration problem

**Comment by tholzheim** [comment]
This issue is caused by a change in the AgGrid API which now overwrites a method of a subclass of AgGrid in another project. See  https://github.com/WolfgangFahl/pyJustpyWidgets/issues/12
So this issue is not related to justpy

**Comment by WolfgangFahl** [comment]
Still the javascript code should not crash - i tried to make it more robust.
